/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author kvnsg
 */
public class Credenciales extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public Credenciales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnCMostrar1 = new javax.swing.JLabel();
        btnCMostrar2 = new javax.swing.JLabel();
        btnCSg = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnCCancelar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnCBack = new javax.swing.JLabel();
        psCPass = new javax.swing.JPasswordField();
        psCCPass = new javax.swing.JPasswordField();

        setMinimumSize(new java.awt.Dimension(400, 500));
        setPreferredSize(new java.awt.Dimension(400, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(400, 500));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(14, 34, 64));
        jLabel1.setText("Crea tu usuario y contraseña");

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(14, 34, 64));
        jLabel2.setText("Usuario");

        txtCUser.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtCUser.setForeground(new java.awt.Color(153, 153, 153));
        txtCUser.setText("Usuario");

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(14, 34, 64));
        jLabel3.setText("Contraseña");

        btnCMostrar1.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        btnCMostrar1.setForeground(new java.awt.Color(14, 34, 64));
        btnCMostrar1.setText("MOSTRAR");
        btnCMostrar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnCMostrar2.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        btnCMostrar2.setForeground(new java.awt.Color(14, 34, 64));
        btnCMostrar2.setText("MOSTRAR");
        btnCMostrar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnCSg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel6.setText("Siguiente");

        javax.swing.GroupLayout btnCSgLayout = new javax.swing.GroupLayout(btnCSg);
        btnCSg.setLayout(btnCSgLayout);
        btnCSgLayout.setHorizontalGroup(
            btnCSgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCSgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        btnCSgLayout.setVerticalGroup(
            btnCSgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCSgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        btnCCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel7.setText("Cancelar");

        javax.swing.GroupLayout btnCCancelarLayout = new javax.swing.GroupLayout(btnCCancelar);
        btnCCancelar.setLayout(btnCCancelarLayout);
        btnCCancelarLayout.setHorizontalGroup(
            btnCCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCCancelarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        btnCCancelarLayout.setVerticalGroup(
            btnCCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCCancelarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        btnCBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCBack.setPreferredSize(new java.awt.Dimension(64, 64));

        psCPass.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        psCPass.setForeground(new java.awt.Color(153, 153, 153));
        psCPass.setText("Contraseña");

        psCCPass.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        psCCPass.setForeground(new java.awt.Color(153, 153, 153));
        psCCPass.setText("Confirmar contraseña");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(psCCPass)
                                .addGap(18, 18, 18)
                                .addComponent(btnCMostrar2)))
                        .addGap(1, 1, 1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(psCPass)
                        .addGap(18, 18, 18)
                        .addComponent(btnCMostrar1))
                    .addComponent(txtCUser)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnCCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(btnCSg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnCBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCMostrar1)
                    .addComponent(psCPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCMostrar2)
                    .addComponent(psCCPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCSg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 580));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btnCBack;
    public javax.swing.JPanel btnCCancelar;
    public javax.swing.JLabel btnCMostrar1;
    public javax.swing.JLabel btnCMostrar2;
    public javax.swing.JPanel btnCSg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JPasswordField psCCPass;
    public javax.swing.JPasswordField psCPass;
    public javax.swing.JTextField txtCUser;
    // End of variables declaration//GEN-END:variables
}
