/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author kvnsg
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        pnlBase = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        lblUser = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblPass = new javax.swing.JLabel();
        lblMostrar = new javax.swing.JLabel();
        lblRUC = new javax.swing.JLabel();
        lblAbrir = new javax.swing.JLabel();
        psfPass = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        btnIngresar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(450, 700));
        setMinimumSize(new java.awt.Dimension(450, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(450, 700));

        pnlBase.setBackground(new java.awt.Color(255, 255, 255));
        pnlBase.setMaximumSize(new java.awt.Dimension(450, 700));
        pnlBase.setMinimumSize(new java.awt.Dimension(450, 700));
        pnlBase.setPreferredSize(new java.awt.Dimension(450, 700));
        pnlBase.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        pnlBase.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 70, -1, -1));

        txtUser.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtUser.setForeground(new java.awt.Color(153, 153, 153));
        txtUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUser.setText("Usuario");
        txtUser.setBorder(null);
        txtUser.setMaximumSize(new java.awt.Dimension(2147483647, 32));
        txtUser.setMinimumSize(new java.awt.Dimension(7, 32));
        txtUser.setPreferredSize(new java.awt.Dimension(47, 32));
        pnlBase.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 390, 30));

        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        pnlBase.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));
        pnlBase.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 367, 430, 10));

        lblPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pass.png"))); // NOI18N
        pnlBase.add(lblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 328, -1, -1));

        lblMostrar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lblMostrar.setForeground(new java.awt.Color(58, 148, 226));
        lblMostrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMostrar.setText("MOSTRAR");
        lblMostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlBase.add(lblMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 70, -1));

        lblRUC.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        lblRUC.setForeground(new java.awt.Color(58, 148, 226));
        lblRUC.setText("Recuperar mi usuario y/o contraseña");
        lblRUC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlBase.add(lblRUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, -1));

        lblAbrir.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        lblAbrir.setForeground(new java.awt.Color(58, 148, 226));
        lblAbrir.setText("Abrir una cuenta");
        lblAbrir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlBase.add(lblAbrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 570, -1, -1));

        psfPass.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        psfPass.setForeground(new java.awt.Color(153, 153, 153));
        psfPass.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        psfPass.setText("Contraseña");
        psfPass.setBorder(null);
        psfPass.setMaximumSize(new java.awt.Dimension(2147483647, 32));
        psfPass.setMinimumSize(new java.awt.Dimension(32, 32));
        psfPass.setPreferredSize(new java.awt.Dimension(32, 32));
        pnlBase.add(psfPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 320, 30));
        pnlBase.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 308, 430, 10));

        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setText("Ingresar");

        javax.swing.GroupLayout btnIngresarLayout = new javax.swing.GroupLayout(btnIngresar);
        btnIngresar.setLayout(btnIngresarLayout);
        btnIngresarLayout.setHorizontalGroup(
            btnIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnIngresarLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        btnIngresarLayout.setVerticalGroup(
            btnIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnIngresarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBase.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 290, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    public javax.swing.JLabel lblAbrir;
    private javax.swing.JLabel lblLogo;
    public javax.swing.JLabel lblMostrar;
    private javax.swing.JLabel lblPass;
    public javax.swing.JLabel lblRUC;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlBase;
    public javax.swing.JPasswordField psfPass;
    public javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
